import { RequestHandler, Response } from 'express';

const languages = {
  af: 'Afrikaans',
  agq: 'Aghem',
  ak: 'Akan',
  sq: 'Albanian',
  am: 'Amharic',
  ar: 'Arabic',
  hy: 'Armenian',
  as: 'Assamese',
  ast: 'Asturian',
  asa: 'Asu',
  az: 'Azerbaijani',
  ksf: 'Bafia',
  bm: 'Bambara',
  bn: 'Bangla',
  bas: 'Basaa',
  eu: 'Basque',
  be: 'Belarusian',
  bem: 'Bemba',
  bez: 'Bena',
  brx: 'Bodo',
  bs: 'Bosnian',
  br: 'Breton',
  bg: 'Bulgarian',
  my: 'Burmese',
  yue: 'Cantonese',
  ca: 'Catalan',
  tzm: 'Central Atlas Tamazight',
  ckb: 'Central Kurdish',
  ccp: 'Chakma',
  ce: 'Chechen',
  chr: 'Cherokee',
  cgg: 'Chiga',
  zh: 'Chinese',
  ksh: 'Colognian',
  kw: 'Cornish',
  hr: 'Croatian',
  cs: 'Czech',
  da: 'Danish',
  dua: 'Duala',
  nl: 'Dutch',
  dz: 'Dzongkha',
  ebu: 'Embu',
  en: 'English',
  eo: 'Esperanto',
  et: 'Estonian',
  ee: 'Ewe',
  ewo: 'Ewondo',
  fo: 'Faroese',
  fil: 'Filipino',
  fi: 'Finnish',
  fr: 'French',
  fur: 'Friulian',
  ff: 'Fulah',
  gl: 'Galician',
  lg: 'Ganda',
  ka: 'Georgian',
  de: 'German',
  el: 'Greek',
  gu: 'Gujarati',
  guz: 'Gusii',
  ha: 'Hausa',
  haw: 'Hawaiian',
  he: 'Hebrew',
  hi: 'Hindi',
  hu: 'Hungarian',
  is: 'Icelandic',
  ig: 'Igbo',
  smn: 'Inari Sami',
  id: 'Indonesian',
  ga: 'Irish',
  it: 'Italian',
  ja: 'Japanese',
  dyo: 'Jola-Fonyi',
  kea: 'Kabuverdianu',
  kab: 'Kabyle',
  kkj: 'Kako',
  kl: 'Kalaallisut',
  kln: 'Kalenjin',
  kam: 'Kamba',
  kn: 'Kannada',
  ks: 'Kashmiri',
  kk: 'Kazakh',
  km: 'Khmer',
  ki: 'Kikuyu',
  rw: 'Kinyarwanda',
  kok: 'Konkani',
  ko: 'Korean',
  khq: 'Koyra Chiini',
  ses: 'Koyraboro Senni',
  nmg: 'Kwasio',
  ky: 'Kyrgyz',
  lkt: 'Lakota',
  lag: 'Langi',
  lo: 'Lao',
  lv: 'Latvian',
  ln: 'Lingala',
  lt: 'Lithuanian',
  nds: 'Low German',
  dsb: 'Lower Sorbian',
  lu: 'Luba-Katanga',
  luo: 'Luo',
  lb: 'Luxembourgish',
  luy: 'Luyia',
  mk: 'Macedonian',
  jmc: 'Machame',
  mgh: 'Makhuwa-Meetto',
  kde: 'Makonde',
  mg: 'Malagasy',
  ms: 'Malay',
  ml: 'Malayalam',
  mt: 'Maltese',
  gv: 'Manx',
  mr: 'Marathi',
  mas: 'Masai',
  mzn: 'Mazanderani',
  mer: 'Meru',
  mgo: 'Metaʼ',
  mn: 'Mongolian',
  mfe: 'Morisyen',
  mua: 'Mundang',
  naq: 'Nama',
  ne: 'Nepali',
  nnh: 'Ngiemboon',
  jgo: 'Ngomba',
  nd: 'North Ndebele',
  lrc: 'Northern Luri',
  se: 'Northern Sami',
  nb: 'Norwegian Bokmål',
  nn: 'Norwegian Nynorsk',
  nus: 'Nuer',
  nyn: 'Nyankole',
  or: 'Odia',
  om: 'Oromo',
  os: 'Ossetic',
  ps: 'Pashto',
  fa: 'Persian',
  pl: 'Polish',
  pt: 'Portuguese',
  pa: 'Punjabi',
  qu: 'Quechua',
  ro: 'Romanian',
  rm: 'Romansh',
  rof: 'Rombo',
  rn: 'Rundi',
  ru: 'Russian',
  rwk: 'Rwa',
  sah: 'Sakha',
  saq: 'Samburu',
  sg: 'Sango',
  sbp: 'Sangu',
  gd: 'Scottish Gaelic',
  seh: 'Sena',
  sr: 'Serbian',
  ksb: 'Shambala',
  sn: 'Shona',
  ii: 'Sichuan Yi',
  si: 'Sinhala',
  sk: 'Slovak',
  sl: 'Slovenian',
  xog: 'Soga',
  so: 'Somali',
  es: 'Spanish',
  zgh: 'Standard Moroccan Tamazight',
  sw: 'Swahili',
  sv: 'Swedish',
  gsw: 'Swiss German',
  shi: 'Tachelhit',
  dav: 'Taita',
  tg: 'Tajik',
  ta: 'Tamil',
  twq: 'Tasawaq',
  tt: 'Tatar',
  te: 'Telugu',
  teo: 'Teso',
  th: 'Thai',
  bo: 'Tibetan',
  ti: 'Tigrinya',
  to: 'Tongan',
  tr: 'Turkish',
  uk: 'Ukrainian',
  hsb: 'Upper Sorbian',
  ur: 'Urdu',
  ug: 'Uyghur',
  uz: 'Uzbek',
  vai: 'Vai',
  vi: 'Vietnamese',
  vun: 'Vunjo',
  wae: 'Walser',
  cy: 'Welsh',
  fy: 'Western Frisian',
  wo: 'Wolof',
  yav: 'Yangben',
  yi: 'Yiddish',
  yo: 'Yoruba',
  dje: 'Zarma',
  zu: 'Zulu',
};

export const retrieveLanguages = (): string[] => {
  return Object.values(languages);
};

export const success = (res: Response, data: string | Object) => {
  return res.status(200).json({
    status: 200,
    message: 'Sucess',
    data: data,
  });
};

export const created = (res: Response, data: string | Object) => {
  return res.status(201).json({
    status: 201,
    message: 'Resource created',
    data: data,
  });
};

export const badRequest = (res: Response, data: string | Object) => {
  return res.status(400).json({
    status: 400,
    error: 'Bad Request',
    message: data,
    data: null,
  });
};

export const serverError = (res: Response, data: string | Object) => {
  return res.status(500).json({
    status: 500,
    error: 'Internal server error',
    message: data,
    data: null,
  });
};

export const notFound = (res: Response, data: string | Object) => {
  return res.status(404).json({
    status: 404,
    error: 'Resource not found',
    message: data,
    data: null,
  });
};

export default {
  retrieveLanguages,
  success,
  badRequest,
  serverError,
  created,
  notFound,
};
